### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript-analyzer#15]
Failure occurs [from here](https://github.com/exercism/javascript-analyzer/blob/master/src/analyzers/index.ts#L19):

```
./bin/analyze.sh two_fer test/fixtures/two-fer/0
/Users/tejas.bubane/opensource/javascript-analyzer/dist/analyzers/index.js:1
Error: Cannot find module './two_fer'
Require stack:
- /Users/tejas.bubane/opensource/javascript-analyzer/dist/analyzers/index.js
- /Users/tejas.bubane/opensource/javascript-analyzer/dist/analyze.js
    at Function.find (/Users/tejas.bubane/opensource/javascript-analyzer/dist/analyzers/index.js:14:22)
    at Object.<anonymous> (/Users/tejas.bubane/opensource/javascript-analyzer/dist/analyze.js:9:45) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tejas.bubane/opensource/javascript-analyzer/dist/analyzers/index.js',
    '/Users/tejas.bubane/opensource/javascript-analyzer/dist/analyze.js'
  ]
}
Cannot find module './two_fer'
Require stack:
- /Users/tejas.bubane/opensource/javascript-analyzer/dist/analyzers/index.js
- /Users/tejas.bubane/opensource/javascript-analyzer/dist/analyze.js%
```

I ran `yarn install` and `yarn build` before. Hope I am not doing something silly here 🙈

**Comment by SleeplessByte** [comment]
You are 😁 

```diff
- ./bin/analyze.sh two_fer test/fixtures/two-fer/0
+ ./bin/analyze.sh two-fer test/fixtures/two-fer/0
```

**Comment by tejasbubane** [comment]
Arghhhh 🙈 Knew it would be something silly.
